import { Student, Subject, Notice, ChatThread, UserProfile, UserRole, SchoolInfo, Project, Task, CalendarEvent, StudentIncidentReport } from '../types';

export const mockSchoolInfo: SchoolInfo = {
  nombre: 'Colegio Lumni de Excelencia',
  cct: '15EPR2345K',
  ciclo: '2026-2027',
  direccion: 'Av. Las Palmas #450, Col. Bosques',
  telefono: '(55) 8432-9011',
  director: 'Mtra. Alejandra Morales Ruiz',
};

export const mockUsers: Record<UserRole, UserProfile> = {
  teacher: {
    id: 'usr_prof_01',
    email: 'carlos.mendoza@colegio.edu.mx',
    nombre: 'Prof. Carlos',
    apellidos: 'Mendoza Morales',
    rol: 'teacher',
    colegio: 'Colegio Lumni de Excelencia',
    grupo: '3er Grado - Grupo B',
    ciclo: '2026-2027',
    maxAlumnos: 50,
    suscripcion: {
      estado: 'activa',
      plan: 'Docente Pro',
      pagoInicial: 250,
      mensualidad: 50,
      fechaInicio: '2026-08-01',
      proximoPago: '01 de Octubre 2026',
      ultimoPagoMonto: 250,
      mesesActivo: 1,
    },
  },
  parent: {
    id: 'usr_tutor_01',
    email: 'laura.soto@correo.com',
    nombre: 'Sra. Laura',
    apellidos: 'Soto Beltrán',
    rol: 'parent',
    colegio: 'Colegio Lumni de Excelencia',
    grupo: '3er Grado - Grupo B',
    ciclo: '2026-2027',
  },
};

export const mockSubjects: Subject[] = [
  { id: 'sub_esp', nombre: 'Español', clave: 'ESP-301' },
  { id: 'sub_mat', nombre: 'Matemáticas', clave: 'MAT-302' },
  { id: 'sub_cien', nombre: 'Ciencias Naturales', clave: 'CIE-303' },
  { id: 'sub_hist', nombre: 'Historia', clave: 'HIS-304' },
  { id: 'sub_civ', nombre: 'Formación Cívica y Ética', clave: 'FCyE-305' },
  { id: 'sub_ing', nombre: 'Inglés', clave: 'ING-306' },
  { id: 'sub_art', nombre: 'Educación Artística', clave: 'ART-307' },
];

export const mockStudents: Student[] = [
  {
    id: 'stu_001',
    matricula: 'LUM-2026-001',
    curp: 'HESM140518HDFRTA03',
    nombre: 'Mateo',
    apellidos: 'Hernández Soto',
    genero: 'M',
    fechaNacimiento: '2014-05-18',
    grado: '3°',
    grupo: 'B',
    turno: 'Matutino',
    activo: true,
    tutorNombre: 'Laura Soto Beltrán',
    tutorTelefono: '55 1234 5678',
    tutorEmail: 'laura.soto@correo.com',
    tutorParentesco: 'Madre',
    asistenciasPorFecha: {
      '2026-09-11': { status: 'presente', hora: '07:54' },
      '2026-09-10': { status: 'presente', hora: '07:50' },
      '2026-09-09': { status: 'retardo', hora: '08:12' },
      '2026-09-08': { status: 'presente', hora: '07:48' },
      '2026-09-07': { status: 'presente', hora: '07:52' },
    },
    asistenciasTotales: {
      presentes: 18,
      retardos: 2,
      faltas: 0,
      justificadas: 0,
    },
    calificacionesTrimestres: {
      1: {
        'Español': 9,
        'Matemáticas': 9,
        'Ciencias Naturales': 10,
        'Historia': 9,
        'Formación Cívica y Ética': 10,
        'Inglés': 9,
        'Educación Artística': 10,
      },
      2: {
        'Español': 9,
        'Matemáticas': 10,
        'Ciencias Naturales': 9,
        'Historia': 9,
        'Formación Cívica y Ética': 10,
        'Inglés': 9,
        'Educación Artística': 10,
      },
      3: {
        'Español': null,
        'Matemáticas': null,
        'Ciencias Naturales': null,
        'Historia': null,
        'Formación Cívica y Ética': null,
        'Inglés': null,
        'Educación Artística': null,
      },
    },
    observaciones: 'Excelente participación en clase y puntualidad destacada.',
  },
  {
    id: 'stu_002',
    matricula: 'LUM-2026-002',
    curp: 'GAPV140822MDFRTA08',
    nombre: 'Valentina',
    apellidos: 'García Pérez',
    genero: 'F',
    fechaNacimiento: '2014-08-22',
    grado: '3°',
    grupo: 'B',
    turno: 'Matutino',
    activo: true,
    tutorNombre: 'Roberto García Nava',
    tutorTelefono: '55 8765 4321',
    tutorEmail: 'rgarcia@correo.com',
    tutorParentesco: 'Padre',
    asistenciasPorFecha: {
      '2026-09-11': { status: 'presente', hora: '07:45' },
      '2026-09-10': { status: 'presente', hora: '07:42' },
      '2026-09-09': { status: 'presente', hora: '07:49' },
      '2026-09-08': { status: 'falta', hora: '--:--', notas: 'Cita médica justificada' },
      '2026-09-07': { status: 'presente', hora: '07:50' },
    },
    asistenciasTotales: {
      presentes: 17,
      retardos: 1,
      faltas: 1,
      justificadas: 1,
    },
    calificacionesTrimestres: {
      1: {
        'Español': 10,
        'Matemáticas': 10,
        'Ciencias Naturales': 10,
        'Historia': 9,
        'Formación Cívica y Ética': 10,
        'Inglés': 10,
        'Educación Artística': 10,
      },
      2: {
        'Español': 10,
        'Matemáticas': 10,
        'Ciencias Naturales': 10,
        'Historia': 9,
        'Formación Cívica y Ética': 10,
        'Inglés': 9,
        'Educación Artística': 10,
      },
      3: {
        'Español': null,
        'Matemáticas': null,
        'Ciencias Naturales': null,
        'Historia': null,
        'Formación Cívica y Ética': null,
        'Inglés': null,
        'Educación Artística': null,
      },
    },
    observaciones: 'Liderazgo positivo y alto rendimiento académico.',
  },
  {
    id: 'stu_003',
    matricula: 'LUM-2026-003',
    curp: 'LORE141103HDFRTA01',
    nombre: 'Emiliano',
    apellidos: 'López Ramos',
    genero: 'M',
    fechaNacimiento: '2014-11-03',
    grado: '3°',
    grupo: 'B',
    turno: 'Matutino',
    activo: true,
    tutorNombre: 'Marisol Ramos Cruz',
    tutorTelefono: '55 3344 5566',
    tutorEmail: 'mramos@correo.com',
    tutorParentesco: 'Madre',
    asistenciasPorFecha: {
      '2026-09-11': { status: 'retardo', hora: '08:08' },
      '2026-09-10': { status: 'presente', hora: '07:55' },
      '2026-09-09': { status: 'presente', hora: '07:58' },
      '2026-09-08': { status: 'presente', hora: '07:52' },
      '2026-09-07': { status: 'falta', hora: '--:--' },
    },
    asistenciasTotales: {
      presentes: 15,
      retardos: 3,
      faltas: 2,
      justificadas: 0,
    },
    calificacionesTrimestres: {
      1: {
        'Español': 8,
        'Matemáticas': 7,
        'Ciencias Naturales': 8,
        'Historia': 8,
        'Formación Cívica y Ética': 9,
        'Inglés': 8,
        'Educación Artística': 9,
      },
      2: {
        'Español': 8,
        'Matemáticas': 8,
        'Ciencias Naturales': 8,
        'Historia': 8,
        'Formación Cívica y Ética': 9,
        'Inglés': 8,
        'Educación Artística': 9,
      },
      3: {
        'Español': null,
        'Matemáticas': null,
        'Ciencias Naturales': null,
        'Historia': null,
        'Formación Cívica y Ética': null,
        'Inglés': null,
        'Educación Artística': null,
      },
    },
    observaciones: 'Requiere reforzar comprensión lectora y tareas de matemáticas.',
  },
  {
    id: 'stu_004',
    matricula: 'LUM-2026-004',
    curp: 'MARS140214MDFRTA05',
    nombre: 'Sofía',
    apellidos: 'Martínez Aguilar',
    genero: 'F',
    fechaNacimiento: '2014-02-14',
    grado: '3°',
    grupo: 'B',
    turno: 'Matutino',
    activo: true,
    tutorNombre: 'Karla Aguilar Domínguez',
    tutorTelefono: '55 9988 7766',
    tutorEmail: 'kaguilar@correo.com',
    tutorParentesco: 'Madre',
    asistenciasPorFecha: {
      '2026-09-11': { status: 'presente', hora: '07:49' },
      '2026-09-10': { status: 'presente', hora: '07:51' },
      '2026-09-09': { status: 'presente', hora: '07:48' },
      '2026-09-08': { status: 'presente', hora: '07:50' },
      '2026-09-07': { status: 'presente', hora: '07:47' },
    },
    asistenciasTotales: {
      presentes: 20,
      retardos: 0,
      faltas: 0,
      justificadas: 0,
    },
    calificacionesTrimestres: {
      1: {
        'Español': 10,
        'Matemáticas': 10,
        'Ciencias Naturales': 10,
        'Historia': 9,
        'Formación Cívica y Ética': 10,
        'Inglés': 10,
        'Educación Artística': 10,
      },
      2: {
        'Español': 10,
        'Matemáticas': 10,
        'Ciencias Naturales': 10,
        'Historia': 10,
        'Formación Cívica y Ética': 10,
        'Inglés': 10,
        'Educación Artística': 10,
      },
      3: {
        'Español': null,
        'Matemáticas': null,
        'Ciencias Naturales': null,
        'Historia': null,
        'Formación Cívica y Ética': null,
        'Inglés': null,
        'Educación Artística': null,
      },
    },
    observaciones: 'Desempeño sobresaliente y gran compañerismo.',
  },
];

export const mockNotices: Notice[] = [
  {
    id: 'not_001',
    titulo: 'Junta Informativa de Evaluación - 1er Trimestre',
    contenido: 'Estimados padres de familia: Se les convoca cordialmente a la primera entrega de boletas y retroalimentación pedagógica este próximo viernes a las 08:30 hrs en el aula escolar.',
    autor: 'Prof. Carlos Mendoza Morales',
    rolAutor: 'Docente Titular',
    fecha: '2026-09-11',
    audiencia: 'padres',
    prioridad: 'alta',
    destacado: true,
  },
  {
    id: 'not_002',
    titulo: 'Conmemoración del Aniversario de la Independencia',
    contenido: 'Recordamos a toda la comunidad escolar que el festival cívico se llevará a cabo el día 15 de septiembre. Los alumnos podrán asistir con vestimenta típica mexicana.',
    autor: 'Mtra. Alejandra Morales Ruiz',
    rolAutor: 'Dirección Escolar',
    fecha: '2026-09-08',
    audiencia: 'todos',
    prioridad: 'media',
    destacado: false,
  },
  {
    id: 'not_003',
    titulo: 'Mantenimiento Preventivo de Servidores Escolares',
    contenido: 'El fin de semana se realizarán actualizaciones del sistema para optimizar la velocidad de carga y sincronización de datos.',
    autor: 'Soporte Técnico Lumni',
    rolAutor: 'Administración',
    fecha: '2026-09-05',
    audiencia: 'profesores',
    prioridad: 'baja',
    destacado: false,
  },
];

export const mockThreads: ChatThread[] = [
  {
    id: 'th_001',
    studentId: 'stu_001',
    studentNombre: 'Mateo Hernández Soto',
    tutorNombre: 'Laura Soto Beltrán',
    tutorTelefono: '55 1234 5678',
    teacherNombre: 'Prof. Carlos Mendoza Morales',
    ultimoMensaje: 'Muchas gracias maestro, estaré puntual en la junta.',
    ultimaFecha: '2026-09-11 14:32',
    mensajesNoLeidos: 0,
    mensajes: [
      {
        id: 'm1',
        remitente: 'teacher',
        texto: 'Buenas tardes Sra. Laura, le comparto que Mateo ha mostrado un avance excelente en el proyecto de Ciencias.',
        timestamp: '14:20',
        leido: true,
      },
      {
        id: 'm2',
        remitente: 'parent',
        texto: 'Muchas gracias profesor, en casa lo hemos estado motivando. ¿Habrá material extra que deba llevar?',
        timestamp: '14:25',
        leido: true,
      },
      {
        id: 'm3',
        remitente: 'teacher',
        texto: 'Por ahora todo va perfecto. Nos vemos en la junta este viernes.',
        timestamp: '14:28',
        leido: true,
      },
      {
        id: 'm4',
        remitente: 'parent',
        texto: 'Muchas gracias maestro, estaré puntual en la junta.',
        timestamp: '14:32',
        leido: true,
      },
    ],
  },
  {
    id: 'th_002',
    studentId: 'stu_003',
    studentNombre: 'Emiliano López Ramos',
    tutorNombre: 'Marisol Ramos Cruz',
    tutorTelefono: '55 3344 5566',
    teacherNombre: 'Prof. Carlos Mendoza Morales',
    ultimoMensaje: 'Enterada profesor, hoy repasaremos las tablas de multiplicar.',
    ultimaFecha: '2026-09-10 11:15',
    mensajesNoLeidos: 1,
    mensajes: [
      {
        id: 'm201',
        remitente: 'teacher',
        texto: 'Buenos días Sra. Marisol. Le comento que sería conveniente repasar las multiplicaciones de dos cifras con Emiliano.',
        timestamp: '10:45',
        leido: true,
      },
      {
        id: 'm202',
        remitente: 'parent',
        texto: 'Enterada profesor, hoy repasaremos las tablas de multiplicar.',
        timestamp: '11:15',
        leido: false,
      },
    ],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj_001',
    titulo: 'Huerto Escolar Sustentable y Biodiversidad',
    campos: ['Saberes y Pensamiento Científico', 'Ética, Naturaleza y Sociedades'],
    fechaPub: '2026-09-02',
    fecha: '2026-09-25',
    desc: 'Investigación sobre el ciclo de vida de las plantas, medición del crecimiento y cultivo de hortalizas en el patio escolar.',
    estado: 'desarrollo',
  },
  {
    id: 'proj_002',
    titulo: 'Antología de Cuentos y Tradiciones Comunitarias',
    campos: ['Lenguajes', 'De lo Humano y lo Comunitario'],
    fechaPub: '2026-09-06',
    fecha: '2026-09-30',
    desc: 'Entrevistas a familiares sobre leyendas locales, redacción de textos narrativos e ilustración de un libro artesanal.',
    estado: 'desarrollo',
  },
  {
    id: 'proj_003',
    titulo: 'Feria de la Ciencia y Energías Limpias',
    campos: ['Saberes y Pensamiento Científico'],
    fechaPub: '2026-09-01',
    fecha: '2026-10-15',
    desc: 'Diseño de maquetas sobre energía solar, eólica e hidráulica para exposición escolar ante la comunidad de padres.',
    estado: 'planeacion',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk_001',
    titulo: 'Resolución de problemas con fracciones y división',
    campos: ['Saberes y Pensamiento Científico'],
    fechaPub: '2026-09-10',
    fecha: '2026-09-15',
    desc: 'Resolver las páginas 24 a 26 del cuaderno de trabajo. Justificar cada respuesta con operaciones completas.',
    estado: 'pendiente',
  },
  {
    id: 'tsk_002',
    titulo: 'Redacción de una reseña biográfica histórica',
    campos: ['Lenguajes', 'Ética, Naturaleza y Sociedades'],
    fechaPub: '2026-09-09',
    fecha: '2026-09-16',
    desc: 'Elegir un personaje destacado de la historia de México, redactar 1 cuartilla destacando sus aportaciones.',
    estado: 'pendiente',
  },
  {
    id: 'tsk_003',
    titulo: 'Cuadro comparativo: Ecosistemas de México',
    campos: ['Saberes y Pensamiento Científico', 'Ética, Naturaleza y Sociedades'],
    fechaPub: '2026-09-08',
    fecha: '2026-09-14',
    desc: 'Completar tabla con flora, fauna y clima de bosque templado, desierto y selva húmeda.',
    estado: 'entregada',
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal_001',
    titulo: 'Inicio del Ciclo Escolar 2026-2027',
    tipo: 'evento',
    fecha: '2026-08-24',
    descripcion: 'Bienvenida general y asignación de aulas.',
  },
  {
    id: 'cal_002',
    titulo: 'Festival Cívico de la Independencia',
    tipo: 'evento',
    fecha: '2026-09-15',
    descripcion: 'Conmemoración del grito de Independencia y festival cívico estudiantil.',
  },
  {
    id: 'cal_003',
    titulo: 'Suspensión Oficial de Labores Docentes',
    tipo: 'suspension',
    fecha: '2026-09-16',
    descripcion: 'Día feriado oficial nacional.',
  },
  {
    id: 'cal_004',
    titulo: 'Entrega: Huerto Escolar Sustentable',
    tipo: 'entrega',
    fecha: '2026-09-25',
    descripcion: 'Presentación de bitácoras y primer muestreo de germinación.',
  },
  {
    id: 'cal_005',
    titulo: 'Consejo Técnico Escolar (CTE)',
    tipo: 'suspension',
    fecha: '2026-09-26',
    descripcion: 'Reunión colegiada docente mensual.',
  },
  {
    id: 'cal_006',
    titulo: 'Evaluación Parcial de Matemáticas',
    tipo: 'evaluacion',
    fecha: '2026-09-29',
    descripcion: 'Examen diagnóstico y formativo del 1er periodo.',
  },
  {
    id: 'cal_007',
    titulo: 'Junta de Entrega de Boletas Trimestrales',
    tipo: 'evento',
    fecha: '2026-10-09',
    descripcion: 'Reunión presencial con tutores y entrega de boletas impresas.',
  },
];

export const mockIncidentReports: StudentIncidentReport[] = [
  {
    id: 'inc_001',
    studentId: 'stu_001',
    studentName: 'Mateo Hernández Soto',
    tipo: 'felicitacion',
    titulo: 'Destacada Participación en Feria de Ciencias',
    descripcion: 'Mateo lideró con gran entusiasmo y responsabilidad su equipo en el experimento del volcán químico, mostrando liderazgo y compañerismo.',
    fecha: '2026-09-10',
    gravedad: 'baja',
    atendido: true,
    docenteNombre: 'Prof. Carlos Mendoza Morales',
  },
  {
    id: 'inc_002',
    studentId: 'stu_002',
    studentName: 'Sofía Valeria Morales Ruiz',
    tipo: 'conducta',
    titulo: 'Uso de Dispositivo Móvil en Hora de Clase',
    descripcion: 'Se le solicitó en dos ocasiones guardar el celular durante la explicación de matemáticas. Se dialogó con ella para evitar distracciones.',
    fecha: '2026-09-08',
    gravedad: 'media',
    compromisoTutor: 'La tutora conversará en casa para respetar el reglamento escolar.',
    atendido: true,
    docenteNombre: 'Prof. Carlos Mendoza Morales',
  },
  {
    id: 'inc_003',
    studentId: 'stu_004',
    studentName: 'Valentina Díaz Castro',
    tipo: 'academico',
    titulo: 'Rezago en Entrega de Tareas de Historia',
    descripcion: 'No se han entregado las últimas 2 actividades de la línea del tiempo histórica. Se invita al tutor a revisar la libreta.',
    fecha: '2026-09-11',
    gravedad: 'media',
    compromisoTutor: 'Se comprometen a regularizar entregas antes del viernes.',
    atendido: false,
    docenteNombre: 'Prof. Carlos Mendoza Morales',
  },
  {
    id: 'inc_004',
    studentId: 'stu_003',
    studentName: 'Santiago Navarro López',
    tipo: 'citatorio',
    titulo: 'Citatorio Presencial con Tutor',
    descripcion: 'Reunión para acordar estrategia de regularización académica y seguimiento socioemocional del alumno.',
    fecha: '2026-09-15',
    gravedad: 'alta',
    atendido: false,
    docenteNombre: 'Prof. Carlos Mendoza Morales',
  },
];

